---
displayName: "CakePHP Example"
description: PHP Stack with PHP 7.1 and a quickstart CakePHP application for OpenShift v3
tags: ["PHP", "Apache", "RHEL"]
icon: /images/type-php.svg
globalMemoryLimit: 2430Mi
