---
displayName: Java Vert.x
description: Java stack with OpenJDK 8 and Vert.x demo application
tags: ["Java", "OpenJDK", "Maven", "Vertx"]
icon: /images/type-spring-boot.svg
globalMemoryLimit: 2674Mi
