---
displayName: Thorntail REST HTTP
description: Quickstart to expose a REST Greeting endpoint using Thorntail
tags: ["Java", "OpenJDK", "Maven", "EAP"]
icon: /images/type-thorntail.svg
globalMemoryLimit: 2674Mi
